# NumPy introduction

### (A) Arrays

In [2]:
import numpy as np

In [4]:
my_list = [1,2,3]

In [5]:
np_array = np.array(my_list)

In [7]:
np_array

array([1, 2, 3])

There are lots of ways to create arrays in NumPy. First off we can create a 2D array.

In [8]:
twod_list = [[1,2,3],[3,4,2],[4,5,9]]

In [9]:
np.array(twod_list)

array([[1, 2, 3],
       [3, 4, 2],
       [4, 5, 9]])

Note this is a 2-dimensional array. It is 3x3 but if we count the number of square brackets needed to open it then we will see that it is infact 2 dimensional. This is a useful site for talk about multi-dimensional arrays https://www.ict.social/python/basics/multidimensional-lists-in-python

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((5,5)) #however many entries there are in the tuple will specify the number of dimensions.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [23]:
np.linspace(0,100,51)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100.])

Identity matrix is very useful for Linear Algebra purposes.

In [25]:
np.eye(5) # Creates a 5x5 identity matrix.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

The following random call has entries generated from a uniform distribution in the 0-1 interval. Another one is randn which has entries distributed by standard normal distribution centred around 0 (so it can include negative values)

In [26]:
np.random.rand(5,5)

array([[0.41350487, 0.29526213, 0.99748606, 0.48567054, 0.8986467 ],
       [0.83035833, 0.83501743, 0.73896231, 0.5753713 , 0.51961242],
       [0.37233828, 0.46889646, 0.69628228, 0.34060468, 0.26397369],
       [0.31458494, 0.45353702, 0.53280986, 0.11713179, 0.99939822],
       [0.1073453 , 0.45503167, 0.21906806, 0.05330923, 0.34400818]])

In [33]:
np.random.randn(5,5)

array([[-1.613278  , -1.29241868,  0.76368098,  0.97487173, -0.27158705],
       [ 0.23186116,  1.31698445,  0.04119172,  1.68825526, -0.02756907],
       [-0.61511051,  0.49536322, -1.32210822,  0.22859964,  0.36085127],
       [-0.7879581 ,  0.84072905,  0.28722207, -1.65650487,  0.28476168],
       [-0.23045154,  1.59323062,  0.53018882, -0.56711517, -0.30532602]])

Generating random integers can be done by using the randomint method. It is inclusive on the low end and exclusive on the high end. 

In [4]:
np.random.randint(1,90,3)

array([31, 42, 57])

In [37]:
story = np.random.randint(0,100,15)

In [38]:
story

array([66, 87, 23, 29, 53, 33, 30, 14, 89, 15, 94, 82, 35, 93, 59])

In [46]:
new_story = story.reshape(3,5)

In [42]:
story.max()

94

In [43]:
story.argmax()

10

In [47]:
new_story.argmax()

10

In [48]:
new_story.shape # note no brackets.

(3, 5)

In [49]:
story.min()

14

In [50]:
story.argmin()

7

In [52]:
 story.dtype

dtype('int64')

This returns the type of datatype in our array, recall that numpy arrays must have all entries of the same datatype, unlike lists.

### (B) NumPy Indexing and Selecting

In [9]:
y = np.arange(1,10,2)
print(y)

[1 3 5 7 9]


In [10]:
y[2:]

array([5, 7, 9])

Numpy arrays differ to normal lists because of their ability to broadcast. Taking a slice of an array just gives a view to the original array. It is not copied. See example below

In [11]:
y[0:2] = 52

In [12]:
print(y)

[52 52  5  7  9]


In [13]:
 slice_arr = y[2:4] = 100

In [14]:
y 

array([ 52,  52, 100, 100,   9])

See how the array y has been changed. To avoid this one must use the array copy function

In [15]:
 arr_copy = y.copy()

In [16]:
arr_copy

array([ 52,  52, 100, 100,   9])

In [17]:
arr_copy[:] = 2

In [18]:
arr_copy

array([2, 2, 2, 2, 2])

In [19]:
y

array([ 52,  52, 100, 100,   9])

Recall how to make a 2D python array.

In [26]:
arr_2d = np.array([[2,3,8],[3,4,0],[5,4,3]]) # this is how we make a 2d array
print(arr_2d)

[[2 3 8]
 [3 4 0]
 [5 4 3]]


In [28]:
arr_2d[1:,:2] # gives the bottom left region

array([[3, 4],
       [5, 4]])

In [29]:
bool_test = np.arange(0,11)

In [30]:
bool_test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
bool_result = bool_test > 6

In [33]:
 bool_test[bool_result] # only returns values that pass the condition aka True.

array([ 7,  8,  9, 10])

In [34]:
# or could've put the variable name inside of itself like so
bool_test[bool_test > 6]

array([ 7,  8,  9, 10])

 ### (C) NumPy Operations

In [3]:
import numpy as np
my_array = np.arange(0,11)

In [4]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#addition, subtraction, scalar all done element wise
my_array + my_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
my_array * my_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
my_array * 6

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

Don't get erros when we divide by zero in NumPy, we just get warnings

In [8]:
my_array / my_array

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
(my_array + 1)/my_array

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 2.        , 1.5       , 1.33333333, 1.25      ,
       1.2       , 1.16666667, 1.14285714, 1.125     , 1.11111111,
       1.1       ])

In [10]:
 np.sqrt(my_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [11]:
np.exp(my_array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [12]:
 np.sin(10)

-0.5440211108893699

In [14]:
np.sin(10%np.pi)

0.5440211108893701

The list of all the universal functions can be found at this link
https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html